### PR TITLE
Create foo.txt

### PR DESCRIPTION
**Pull request by liamdebeasi**

### CODE REVIEW

**Comment by sean-perkins** [comment]
So it only added me for review, maybe because my name is first in the CODEOWNERS file 🤷

**Comment by liamdebeasi** [comment]
Ryan hasn't accepted the invite yet, so he's not a "valid codeowner" yet. Your name didn't pop up here until you accepted the invite.

**Comment by rwaskiewicz** [comment]
Oh hey, look there I am. Someone wanna approve and see how this works?

**Review by rwaskiewicz — DISMISSED** [review]

**Review by sean-perkins — APPROVED** [review]
I approve

**Comment by liamdebeasi** [comment]
Please approve this fix is urgently needed

**Comment by rwaskiewicz** [comment]
Screenshot 2023-02-07 at 3 51 05 PM

Screenshot 2023-02-07 at 3 51 22 PM

**Comment by rwaskiewicz** [comment]
Yay! I was wrong 🎉

**Comment by rwaskiewicz** [comment]
Maybe not...I self-requested a review, but that's not gating the merge?

**Comment by liamdebeasi** [comment]
🤔 
image

**Comment by sean-perkins** [comment]
You already approved - you cannot unapprove. That's illegal

**Comment by rwaskiewicz** [comment]
Apparently, asking for a re-review !== dismissing. TIL

**Comment by liamdebeasi** [comment]
Oh there we go! Once you dismissed your stale review it blocked merging: 
image

**Comment by rwaskiewicz** [comment]
Screenshot 2023-02-07 at 3 53 39 PM

**Comment by liamdebeasi** [comment]
If Sean approved and a non-code owner approved, would that still allow merging? Branch protection rules state that 2 reviews are required. Unsure if a code owner is considered required in this case.

**Comment by sean-perkins** [comment]
Yeah I don't know what/if anything stops us from saying "2 reviewers required", but Amanda & I review; without the team lead reviewing, allowing the merge to happen. 

Is that just a no-no? We trust people and inform them of the process (it would still leave the team lead as a reviewer).

**Comment by liamdebeasi** [comment]
Let me check

**Review by averyrousseau — APPROVED** [review]
👀

**Comment by liamdebeasi** [comment]
Thanks!

image

**Comment by liamdebeasi** [comment]
I'm going to remove Sean as a codeowner and see if that still allows merging.

edit: No change: 
image

**Comment by liamdebeasi** [comment]
I was missing the following branch protection rule: 
image

With that preference enabled:

When Sean was **not** a Code Owner, merging was blocked. Even though 2 reviewers had approved, 0 codeowners had approved.

What Sean was a Code Owner, merging was enabled. There were 2 approvals, with 1 of them being from a codeowner.

**Pull request merged**
